### ISSUE TITLE
uncomment `AssetsClaimed` event assertions on `asset-trap` integration tests

### ISSUE THREAD

**Issue by bernardoaraujor** [paritytech/trappist#114]
follow up to #109 

`pallet-xcm` introduced `AssetsClaimed` event only after v0.9.31

integration tests for `TrappistDropAsset` have assertions commented out until trappist dependencies have been updated accordingly.

https://github.com/paritytech/trappist/blob/098634ea6ffe0ce24caba9f12fc76a677b9ec197/integration-tests/asset-trap/1_trap_claim_native_asset.yml#L142

https://github.com/paritytech/trappist/blob/098634ea6ffe0ce24caba9f12fc76a677b9ec197/integration-tests/asset-trap/2_trap_claim_reserved_asset.yml#L202

https://github.com/paritytech/trappist/blob/098634ea6ffe0ce24caba9f12fc76a677b9ec197/integration-tests/asset-trap/3_trap_claim_native_and_reserved.yml#L236

**Comment by evilrobot-01** [comment]
Reliant on #97
