### ISSUE TITLE
[Trappist on Rococo] Benchmarking setup for Trappist

### ISSUE THREAD

**Issue by hbulgarini** [paritytech/trappist#141]
As part of the deployment of Trappist on Rococo (#138) we will need to benchmark the pallets implemented on the runtime. For this we should get in contact with the DevOps team so we can request a machine with the specified hardware to benchmark the pallets. 

In addition to this we might consider some automation similar to the benchmarking bot that is actually configured for Substrate repository.

**Comment by kalaninja** [comment]
@alvicsam will help us to setup the bot. Here is the [issue](https://github.com/paritytech/ci_cd/issues/798)

**Comment by kalaninja** [comment]
Closed by https://github.com/paritytech/ci_cd/issues/798
