### ISSUE TITLE
[Trappist on Rococo] Configure Trappist Faucet

### ISSUE THREAD

**Issue by stiiifff** [paritytech/trappist#146]
- Once Trappist is live on Rococo, create a faucet account and fund it (manually, from one of the pre-funded accounts)
- Deploy the Faucet based on [Polkadot Testnet faucet](https://github.com/paritytech/polkadot-testnet-faucet)
- Create public Element channel for Trappist faucet fund requests

**Comment by hbulgarini** [comment]
https://paritytech.github.io/polkadot-testnet-faucet/trappist
