### ISSUE TITLE
[0.9.40] Change `WeightToFee` struct to charge for proof size weight.

### ISSUE THREAD

**Issue by hbulgarini** [paritytech/trappist#169]
As per it was described in the following issues/PRs:

https://github.com/paritytech/cumulus/issues/2322
https://github.com/paritytech/substrate/pull/13612
https://github.com/paritytech/cumulus/pull/2326

We should add the `proof_size` calculation to the `WeightToFee` structure.

**Comment by stiiifff** [comment]
@hbulgarini @valentinfernandez1 We can close this one, right ?
