### ISSUE TITLE
Discussion - Seedling runtime for deployment.

### ISSUE THREAD

**Issue by hbulgarini** [paritytech/trappist#192]
A Seedling runtime serves to facilitate the transition for parachain auction winners migrating a blockchain from a different consensus system to the consensus system of a designated Relay Chain. This runtime can also be utilized by new projects to deploy a "bare-bones" parachain, primarily to secure the slot. The team can then proceed at their own pace to deploy the complete runtime. Regardless of the scenario, migration from the Seedling runtime to the full runtime is carried out via the `soloToPara` pallet, which effectively resets the parachain head on the Relay Chain.

The procedure to activate the full runtime is as follows:

1) The Seedling Parachain is registered on the Relay Chain.
2) The parachain slot is won.
3) Seedling commences block generation.
4) Utilizing sudo within Seedling, `soloToPara` is executed, where the new validation code (runtime) and the new head are inputted.
5) New collators are set up with the new runtime and genesis head data.
6) Upon execution of `soloToPara`, the validation code and head data are updated on the Relay Chain, rendering your Seedling collators incapable of continuing block production. As a result, Seedling collators are halted.
7) The new collators assume responsibility and initiate block production.

Alternatively, another deployment pathway involves taking a parachain template, modifying the chain specs with the necessary setup, and implementing a pallet that restricts operations on the parachain. Examples of these pallets are:

https://github.com/paritytech/trappist/tree/main/pallets/lockdown-mode
https://github.com/paritytech/substrate/pull/12092

Initially, the parachain can be launched with halted operations using any of these pallets. Once the team is prepared, they can execute a runtime upgrade and remove the filter. As per my understanding, this second method would not necessitate any restart or collator switch.

The discussion to be had here revolves around the optimal deployment pathway when a team has yet to prepare its runtime, but wishes to secure the slot.

**Comment by peterwht** [comment]
One concern that parachain builders need to take into account is that Seedling is not DDoS secure. Because Seedling does not have the concept of fees or currency, it does not have protection again a DDoS attack.

However, for new parachains, Seedling can be a good starting point if someone wants to win an auction slot and have a placeholder until the full-runtime is ready.

Seedling can also be used as the starting point, and runtime upgrades can be performed on it. So, start with Seedling and iteratively perform runtime upgrades to add functionality -- without ever using `soloToPara` to migrate. This does not require lockdown-mode as Seedling is already limited to Sudo calls.

Should Trappist deploy with Seedling? I personally would say no, unless it is done as a learning experience. Trappist already has a full-runtime built that can be deployed right away. Seedling is, generally, used for projects that want a placeholder while the full runtime is built. And, doing a `soloToPara` migration would complicate deploying as it requires two sets of collators which is unnecessary in the case of Trappist.

**Comment by hbulgarini** [comment]
Thanks for the reply @peterwht! your insights are super useful.

The idea to raise this discussion on Trappist is not because there is a functional or technical need to use seedling, as you mentioned the runtime is fully functional and it can be easily be used as it is. However, the Trappist deployment into Rococo is a perfect scenario for documenting the best deployment good practices and this is the reason why we are considering using seedling.

Personally, i'm more in favor of the second option: deploy a parachain template with the chain specs configured and the lockdown mode activated. I think it removes some sensitive step as the head replacement on the relay chain and it also avoids the collators restart. Do i'm missing anything in this conclusion?

**Comment by peterwht** [comment]
Hector, the second option makes a lot of sense to me too. There is something to consider as well: why do you need the lockdown mode? Remember, the chain's currency has to be issued to someone. So, if _only one_ user has any currency, then that means no-one else can submit a transaction. In other words, currency should not be transferred or minted into anyone's account except (for example) the Sudo account. This ensures that _only_ the Sudo account can use the chain, and hence lockdown pallets are not required. And once the chain is ready, currency can be distributed.

I do like the idea of starting with a simple parachain template and upgrading in small iterations.

**Comment by hbulgarini** [comment]
> Remember, the chain's currency has to be issued to someone. So, if only one user has any currency, then that means no-one else can submit a transaction. 

This is true, but i can imagine on edge cases where depending how the parachain is configured some assets might be minted through XCM messages, so the lockdown might cover this as well. However this could be achieved as well by changing the `XcmReserveTransferFilter` and `XcmTeleportFilter` configs to `Nothing`.

**Comment by hbulgarini** [comment]
@stiiifff just a reminder to identify if we should create a "seedling" runtime before deployment or go directly with the current runtime.

**Comment by stiiifff** [comment]
Closing this as per last comment.
