### ISSUE TITLE
[0.9.40] Add `query_account_balances` runtime api for pallet assets.

### ISSUE THREAD

**Issue by hbulgarini** [paritytech/trappist#199]
During release 0.9.40, the `query_account_balances` runtime api for querying the assets balances were implemented.

We can have the details here:
https://github.com/paritytech/substrate/pull/13352

This is what it has to be added in the runtime (please check the [assets_common](https://github.com/paritytech/cumulus/blob/master/parachains/runtimes/assets/common/src/runtime_api.rs#L32)):
```rust
	impl assets_common::runtime_api::FungiblesApi<
		Block,
		AccountId,
	> for Runtime
	{
		fn query_account_balances(account: AccountId) -> Result<xcm::VersionedMultiAssets, assets_common::runtime_api::FungiblesAccessError> {
			use assets_common::fungible_conversion::{convert, convert_balance};
			Ok([
				// collect pallet_balance
				{
					let balance = Balances::free_balance(account.clone());
					if balance > 0 {
						vec![convert_balance::<KsmLocation, Balance>(balance)?]
					} else {
						vec![]
					}
				},
				// collect pallet_assets (TrustBackedAssets)
				convert::<_, _, _, _, TrustBackedAssetsConvertedConcreteId>(
					Assets::account_balances(account.clone())
						.iter()
						.filter(|(_, balance)| balance > &0)
				)?,
				// collect pallet_assets (ForeignAssets)
				convert::<_, _, _, _, ForeignAssetsConvertedConcreteId>(
					ForeignAssets::account_balances(account)
						.iter()
						.filter(|(_, balance)| balance > &0)
				)?,
				// collect ... e.g. other tokens
			].concat().into())
		}
	}
```

CC: @stiiifff @valentinfernandez1

**Comment by valentinfernandez1** [comment]
I like this implementation. We would have to remove this part since we don't have `ForeignAssets`.
```rust
                                ....
                                // collect pallet_assets (ForeignAssets)
				convert::<_, _, _, _, ForeignAssetsConvertedConcreteId>(
					ForeignAssets::account_balances(account)
						.iter()
						.filter(|(_, balance)| balance > &0)
				)?,
```
But everything else looks good to me. I can add it today. 

In regards to your second comment, why do you consider that both `convert_ref` should coexist in the same file??

**Comment by hbulgarini** [comment]
> In regards to your second comment, why do you consider that both convert_ref should coexist in the same file??

Basically because i'm not 100% sure which changes are needed over the asset registry by using the new `convert_ref` function. In case we need to change something (if it's technically feasible), i would apply these new impls from `assets_common` and implement the runtime api and once that is ready in a different PR i would modify the old impls by the new ones. However i saw that in your draft PR #202 you have to modify the `FungiblesAdapter`, so probably everything should be changed in one PR.

**Comment by stiiifff** [comment]
@valentinfernandez1 Closing this as I believe this was done, right ? Re-open if not.
