### ISSUE TITLE
Remove restriction from asset registry.

### ISSUE THREAD

**Issue by hbulgarini** [paritytech/trappist#212]
At the moment only assets from a pallet instance can be reserved transferred from any chain to trappist:

```rust
			ensure!(
				matches!(
					asset_multi_location,
					MultiLocation {
						parents: 1,
						interior: Junctions::X3(Parachain(_), PalletInstance(_), GeneralIndex(_))
					}
				),
				Error::<T>::WrongMultiLocation
			);
```

This check is too restrictive and for example it does not let to register the case of receiving a native token from any chain and minting it using the asset pallet on trappist.

**Comment by valentinfernandez1** [comment]
We could make the restriction more flexible to ensure that the asset comes either from a parachain directly meaning is the native token or a general index meaning is an id for an asset.

This could be done by ensuring that the last item of the junctions is either of those options. Here's an example of this that could work.

```rust
// verify MultiLocation is valid
ensure!(Self::valid_location(&asset_multi_location), Error::<T>::WrongMultiLocation);
```
```rust
impl<T: Config> Pallet<T> {
	fn valid_location(location: &MultiLocation) -> bool {
		let last_junction = location.last();

		if let Some(junction) = last_junction {
			match junction {
				xcm::v1::Junction::Parachain(_) | xcm::v1::Junction::GeneralIndex(_) => true,
				_ => false,
				}
		} else {
			false
		}
	}
}
```

**Comment by stiiifff** [comment]
@valentinfernandez1 I would prefer a more exhaustive check on the location .. let's not take shortuct (I know `register_reserver_asset` must be called by a privileged origin but still ..).

**Comment by valentinfernandez1** [comment]
That's the challenge here, adding a restriction to the format of the multilocation that is not to restrictive like the one we currently have, but that it's also exhaustive enough to block requests with an unsupported multilocation is not as simple.

As I see it we have different alternatives:
+ Remove the restriction all together as suggested by hector
+ Have a generalized restriction that can block most incorrectly formatted requests, like the one I previously listed.
+ Have a set list of accepted multilocation formats that are allowed and compare the received multilocation to verify that matches with that format.

That's why I suggested [this](https://github.com/paritytech/trappist/issues/212#issuecomment-1582991132) implementation since it feels like a middle ground and we can tweak it to be as flexible or as restrictive as we want.

**Comment by valentinfernandez1** [comment]
After reading  [XCM format - Concrete Identifiers](https://github.com/paritytech/xcm-format#concrete-identifiers) I managed to get a new iteration of this code that allows for contracts and assets outside of substrate. And completely removes Junctions that are not supported.
```rust
	impl<T: Config> Pallet<T> {
		fn valid_location(location: &MultiLocation) -> bool {
			let (split_multilocation, last_junction) = location.clone().split_last_interior();

			if let Some(junction) = last_junction {
				match junction {
					AccountId32{..} | AccountKey20{..}  => true,
					GeneralIndex(_) => {
						let penultimate = split_multilocation.last();
						if let Some(junction) = penultimate {
							match junction {
								PalletInstance(_) => true,
								_ => false
							}
						}else {false}
					},
					_ => false,
				}
			} else {
				false
			}
		}
	}
```

**Comment by hbulgarini** [comment]
> After reading [XCM format - Concrete Identifiers](https://github.com/paritytech/xcm-format#concrete-identifiers) I managed to get a new iteration of this code that allows for contracts and assets outside of substrate. And discards junctions that are not supported.
> 
> ```rust
> fn valid_location(location: &MultiLocation) -> bool {
>     let (split_multilocation, last_junction) = location.clone().split_last_interior()
>     if let Some(junction) = last_junction {
> 	match junction {
> 	    AccountId32 { .. } | AccountKey20 { .. } => true,
> 	    GeneralIndex(_) => {
> 		let penultimate = split_multilocation.last();
> 		if let Some(junction) = penultimate {
> 		    match junction {
> 			PalletInstance(_) => true,
> 			_ => false,
> 		    }
> 		} else {
> 		    false
> 		}
> 	   },
>            PalletInstance(_) => true,
> 	    _ => false,
>         }
>     } else {
> 	false
>     }
> }
> ```
> 
> I am aware that this does not check the first junctions in the InteriorMultilocation, I'm still not sure how to do that in a generalized way.

I think this set up looks good enough and we are covering the needs we have: native tokens and assets and if we are adding smart contracts asset much better then. We should ensure that we have proper unit testing for each case.

**Comment by hbulgarini** [comment]
Done by #224
