### ISSUE TITLE
Update `pallet_uniques` string limits.

### ISSUE THREAD

**Issue by peterwht** [paritytech/trappist#297]
**Motivation**
The current `pallet-uniques` configuration for `StringLimit` is too low, at 50 bytes. Users of uniques often store the IPFS CID in the metadata. These CIDs are larger than 50 bytes. 

Furthemore, the `ValueLimit` seems too high at 256 bytes. The value applies to attributes, which would rarely reach 256 bytes.

**Suggested Solution**

I recommend updating the configuration to use the same as Polkadot's asset hub. 
https://github.com/paritytech/polkadot-sdk/blob/master/cumulus/parachains/runtimes/assets/asset-hub-polkadot/src/lib.rs#L683

- `StringLimit = 128`
- `KeyLimit = 32`
- `ValueLimit = 64`

**Comment by stiiifff** [comment]
Closed by #298
