### ISSUE TITLE
Fix docker image tags

### ISSUE THREAD

**Issue by BulatSaif** [paritytech/trappist#332]
The last two versions of the Docker image at https://hub.docker.com/r/paritytech/trappist/tags contain incorrect tags:

Current tags: trappist-v1.3.0, trappist-v1.1.0
Expected tags: v1.3.0, v1.1.0

This discrepancy impacts our automation, which detects new versions and notifies us about updates, but it fails to detect custom versioning.

The older releases contained the correct version, such as [v1.0.0](https://hub.docker.com/layers/paritytech/trappist/v1.0.0/images/sha256-0ab0cb8e2072518fbb679d6ad43d1319f8b280467608f06efa205446c9aa26de?context=explore).

**Comment by metricaez** [comment]
Done for v1.3.1 and pushing new Docker image with fixed tag. 

Will fix tag for previous releases but is Docker image needed ?

**Comment by BulatSaif** [comment]
https://hub.docker.com/r/paritytech/trappist/tags 
![image](https://github.com/paritytech/trappist/assets/24387396/ebba068d-9525-4d8a-a19c-db7565f9bfdb)

I see `trappist-v1.3.1` not  `v1.3.1`

**Comment by BulatSaif** [comment]
> Will fix tag for previous releases but is Docker image needed ?

No need to fix old versions, just future versions

**Comment by metricaez** [comment]
Done, feel free to close :)
