### ISSUE TITLE
Define 3 XCM / DeFi  use cases

### ISSUE THREAD

**Issue by hbulgarini** [paritytech/trappist#42]
Define 3 uses cases that integrates the DEX pallet located in https://github.com/Wiezzel/substrate-dex with Trappist parachain.

We might use the HOP native token of Trappist to define a some liquidity pool and have a custom logic around the LP token.

- [x] 1. https://github.com/paritytech/trappist/issues/44
- [ ] 2. 
- [ ] 3.

@Wiezzel @bidzyyys @pawanbisht62

**Comment by stiiifff** [comment]
Yes I think so. Let's re-discuss further what a good use case for the `ExchangeAsset` instruction would be, and then we'll create a new issue for it with a proper spec.
