### ISSUE TITLE
Implement DEX pallet in the trappist runtime.

### ISSUE THREAD

**Issue by hbulgarini** [paritytech/trappist#43]
Implement DEX pallet located in https://github.com/Wiezzel/substrate-dex into Trappist runtime.

In case there are some parameters to define let's bring the discussion here.

**Comment by Wiezzel** [comment]
@hbulgarini There's a bunch of constants to configure for the dex pallet:
* `PalletId` – Pallet ID. Used for account derivation.
* `ProviderFeeNumerator` – Numerator of the fractional number representing liquidity provider fee. Should be lower than
the denominator (fees cannot exceed 100%).
* `ProviderFeeDenominator` – Denominator of the fractional number representing liquidity provider fee.
* `MinDeposit` – Minimum amount of currency which must be deposited when creating a new exchange.

I believe `PalletId` doesn't really matter. We just need *some* ID.

Provider fee is something we can potentially tweak. For tests I used the same value which original Uniswap V1 uses, i.e. `0.3%`.

`MinDeposit` – I'm not sure about this one. How much HOPS is considered a reasonable min deposit? In real-world use case it shouldn't be too low to avoid tx spamming, but here it's monopoly money anyway.

**Comment by bidzyyys** [comment]
> PalletId(*b"trappist/dex");
`PalletId` must be 8 characters; My proposal is: `PalletId(*b"py/trdex")`

**Comment by Wiezzel** [comment]
> > PalletId(*b"trappist/dex");
> 
> `PalletId` must be 8 characters; My proposal is: `PalletId(*b"py/trdex")`

How about `trappdex`? To me the meaning of `py/trdex` is a bit unobvious.
