### ISSUE TITLE
Breaking change on pallet_asset_tx_payment for polkadot-v.0.28 release.

### ISSUE THREAD

**Issue by hbulgarini** [paritytech/trappist#48]
This PR https://github.com/paritytech/substrate/pull/11690(Companion on cumulus https://github.com/paritytech/cumulus/pull/1377) introduces a breaking change over the pallet_asset_tx_payment used in Trappist runtime. For the records, this change is adding events for the pallet so we should add the event associated type for the Config trait as it was done on Statemine.

When we bump our substrate version to polkadot-v0.9.28 we should update our runtime accordingly.

**Comment by bernardoaraujor** [comment]
I have a working fix on https://github.com/bernardoaraujor/trappist/tree/48-pallet-asset-tx-payment-event

waiting for https://github.com/Wiezzel/substrate-dex/pull/28 to be merged so that I can remove my `substrate-dex` fork from the dependencies and send a PR here
