### ISSUE TITLE
Brainstorming: Create a XCM dialect example.

### ISSUE THREAD

**Issue by hbulgarini** [paritytech/trappist#62]
There is an on-going discussion about implementing a common XCM dialects, letting the receiving systems to interpret all calls triggered by the `Transact` instructions.

As stated by Rob H the goal of having a common XCM dialect would work as a predictable and common API surface for remote systems with respect to:

- Which operations they support
- How to construct Xcm::Transact packets that can achieve those operations.

The idea of implementing this example on Trappist is not to define the base for developing standards, but more to provide an exploring platform based on a non production real use case.  Also as discussed with @KiChjang , this initiative might result in useful feedback for any XCM protocol change needed in regards to Dialects and versioning management.

We might focus on just one use case around our DEX pallet using the AMM functionalities. Something like:

```
Transact {
    payload: encode![Amm::Swap]
}
```

I see some prerequisites before we can start working on this:

1) Bring another parachain runtime besides the existing one on Trappist. We might create a `parachains` or `runtimes` folder and include have different runtimes with the same dependencies. 
2) There is some work to be done on XCM v2 and v3 to include the logic for Dialects. Potentially there should be a version negotiations process implemented according to this [comment](https://github.com/paritytech/polkadot/issues/6013#issuecomment-1254782842).

Reading resources:
- https://forum.polkadot.network/t/xcm-dialects-plugging-into-xcm-to-create-standardized-and-predictable-api-surfaces/384
- https://github.com/paritytech/polkadot/issues/6013
- https://github.com/paritytech/xcm-format/issues/30

**Comment by stiiifff** [comment]
Really interesting stuff, makes total sense to me ! However, re. the example you proposed, is this a "good example" ?
My understanding was that we want to avoid exposing operations that will lead to "chatty cross-chain interactions".
Just a thought .. let me know what you think.

**Comment by stiiifff** [comment]
Un-assigning @bidzyyys as he is currently busy with other tasks.

**Comment by hbulgarini** [comment]
This approach was dismissed so there is no point on keeping this issue.
