### ISSUE TITLE
call asset_exists function in pallet-asset-registry

### ISSUE THREAD

**Issue by bernardoaraujor** [paritytech/trappist#94]
**Motivation**

[`pallet-asset-registry` is currently using `T::Assets::minimum_balance(asset_id).is_zero()` as a way to verify whether some Asset exists on Trappist's `pallet-assets`](https://github.com/paritytech/trappist/blob/56369530620d4d88398fad00b8206070e1a2f9c2/pallets/asset-registry/src/lib.rs#L149).

That is a bit hacky, and served as motivation for https://github.com/paritytech/substrate/issues/12444

**Suggested Solution**

Ever since https://github.com/paritytech/substrate/pull/12782 was merged, we can replace https://github.com/paritytech/trappist/blob/56369530620d4d88398fad00b8206070e1a2f9c2/pallets/asset-registry/src/lib.rs#L150 with a simpler call to `asset_exists`.

**Comment by bernardoaraujor** [comment]
https://github.com/paritytech/substrate/pull/12782 only got into the release pipeline [after `polkadot-v0.9.35`](https://github.com/paritytech/substrate/blob/polkadot-v0.9.35/frame/assets/src/impl_fungibles.rs)

so that's also a prerequisite: Trappist needs to be using substrate on `polkadot-v0.9.35` or later

**Comment by evilrobot-01** [comment]
So glad that was finally added.

**Comment by stiiifff** [comment]
Depends on https://github.com/paritytech/trappist/issues/122

**Comment by stiiifff** [comment]
Closed by #131
