### ISSUE TITLE
Chess Pallet: an experiment on XCM gamification

### ISSUE THREAD

**Issue by bernardoaraujor** [paritytech/trappist#95]
During the Sardinia Engineering Retreat, I was dealing with heavy addiction to chess.com. I had several matches going on simultaneously, and couldn't stop looking at my phone to think about my next moves.

So I started writing [pallet-chess](https://github.com/SubstrateChess/pallet-chess/) for fun. It was a nice ice-breaker for technical conversations and relatively easy to code. I had many chats with fellow chess-players @peterwht and @CurlyBracketEffect about it.

Chatting with @stiiifff the idea came up of adding this pallet to Trappist. Since Trappist is soon joining Rococo as a parachain, this could be an interesting way to test XCM integrations there. For example:

- Users bring foreign assets via XCM (e.g.: USDt/MOVR/KAR). A deposit is required for the challenger to create a match. An equal deposit is required for the opponent to join the match. Winner takes both deposits.

**Comment by stiiifff** [comment]
Depends on #122

**Comment by ayushmishra2005** [comment]
@stiiifff 

As I understood, we have to add https://github.com/SubstrateChess/pallet-chess to trappist.

Should I add entire pallet and integrate in runtime Or only integrate in runtime by importing https://github.com/SubstrateChess/pallet-chess?

**Comment by stiiifff** [comment]
@ayushmishra2005 Integrate it with a git-based dependency (like e.g. the DEX pallet).

**Comment by stiiifff** [comment]
As we have discovered with PR #133, this [issue](https://github.com/SubstrateChess/pallet-chess/issues/11) in the Chess pallet should first be resolved before it can be included in Trappist's runtime. Moving this issue to milestone 2.

**Comment by bernardoaraujor** [comment]
@sacha-l I wrote the chess pallet so I'd be glad to help!

[this issue](https://github.com/SubstrateChess/pallet-chess/issues/11) should be unblocked soon

But something important to keep in mind is the fact that there's no UI written for this. Currently, the only way to interact with the pallet is via [FEN](https://en.wikipedia.org/wiki/Forsyth%E2%80%93Edwards_Notation) strings written as extrinsic parameters.

I think something like [chessboardjs](https://chessboardjs.com/) could be combined with PolkadotJS API for a frontend, but that's outside of my skillset and unfortunately it's not something I can commit to deliver.

**Comment by stiiifff** [comment]
@bernardoaraujor I pushed my WIP changes over [here](https://github.com/stiiifff/pallet-chess/tree/sde-on-initialize-weight-limits).

**Comment by bernardoaraujor** [comment]
thanks to @lana-shanghai 's help, the [`on_initialize` problem](https://github.com/SubstrateChess/pallet-chess/issues/11) is now solved and this issue should be unblocked

**Comment by stiiifff** [comment]
@bernardoaraujor @lana-shanghai That's an amazing news, moving back this issue to milestone 2 then.
